"""Run a disposable SQLite lab and refresh its two recorded result files."""
import json
import sqlite3
import sys
from datetime import datetime, timezone
from pathlib import Path

HERE = Path(__file__).resolve().parent
EXPECTED = {
    "inner_join": [("Ada", 101), ("Ada", 102), ("Lin", 103)],
    "left_join": [("Ada", 101), ("Ada", 102), ("Lin", 103), ("Sam", None)],
    "no_orders": [("Sam",)],
    "order_counts": [("Ada", 2), ("Lin", 1), ("Sam", 0)],
    "paid_orders_keep_customers": [("Ada", 101), ("Lin", 103), ("Sam", None)],
}

with sqlite3.connect(":memory:") as database:
    database.execute("PRAGMA foreign_keys = ON")
    database.executescript((HERE / "schema.sql").read_text(encoding="utf-8"))
    results = {}
    for block in (HERE / "queries.sql").read_text(encoding="utf-8").split("-- query: ")[1:]:
        name, query = block.split("\n", 1)
        rows = database.execute(query).fetchall()
        if rows != EXPECTED[name]:
            raise AssertionError(f"{name}: expected {EXPECTED[name]!r}, got {rows!r}")
        results[name] = {"passed": True, "rows": rows}
        print(f"PASS {name}: {rows}")
    if set(results) != set(EXPECTED):
        raise AssertionError("Missing example queries")

report = {"ranAt": datetime.now(timezone.utc).isoformat(), "python": sys.version.split()[0],
          "sqlite": sqlite3.sqlite_version, "results": results}
destination = HERE.parent / "results"
destination.mkdir(exist_ok=True)
(destination / "output.json").write_text(json.dumps(report, indent=2) + "\n", encoding="utf-8")
lines = ["# Executed JOIN results", "", "Generated by `code/run_example.py`; all five expected-row checks passed.", "",
         f"Run: {report['ranAt']} · Python {report['python']} · SQLite {report['sqlite']}", ""]
for name, result in results.items():
    lines += [f"## {name}", "", "```json", json.dumps(result["rows"], indent=2), "```", ""]
lines += ["## Interpretation and limits", "", "The LEFT JOIN preserves Sam; COUNT(o.id) correctly reports zero orders. The paid-order ON condition keeps Sam too.", "",
          "This is a small SQLite correctness example, not a performance benchmark or proof of your task completion. Write your own reflection and attach your evidence when ready.", "",
          "[Theory](../theory/01-worked-example.md) · [Queries](../code/queries.sql) · [Machine-readable output](output.json)", ""]
(destination / "evidence.md").write_text("\n".join(lines), encoding="utf-8")
